services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale-p4p
    hostname: clarence-p4d
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    env_file:
      - .env
    volumes:
      - ./tailscale/config:/etc/tailscale
      - ./tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  haproxy:
    build: ./haproxy
    container_name: haproxy-p4p
    env_file:
      - .env
    volumes:
      - ./haproxy:/etc/haproxy
    network_mode: service:tailscale
